"""Royal Oak–inspired demo catalog definitions for storefront seeding."""
from __future__ import annotations

from typing import Any

SEED_PRODUCT_SLUG_PREFIX = "rfp-"

BRANDS: list[dict[str, Any]] = [
    {
        "name": "Royal Furniture Pro",
        "slug": "royal-furniture-pro",
        "description": "Premium home and office furniture crafted for Indian homes.",
        "image": "brand",
    },
    {
        "name": "Italian Living",
        "slug": "italian-living",
        "description": "Italian-inspired luxury sofas, beds and dining collections.",
        "image": "sofa",
    },
    {
        "name": "Malaysian Wood",
        "slug": "malaysian-wood",
        "description": "Solid wood furniture with Malaysian craftsmanship.",
        "image": "dining",
    },
]

CATEGORIES: list[dict[str, Any]] = [
    {
        "name": "Living",
        "slug": "living",
        "featured": True,
        "order": 1,
        "image": "living",
        "subs": [
            {
                "name": "Sofas",
                "slug": "sofas",
                "image": "sofa",
                "unders": [
                    ("Fabric Sofa", "fabric-sofa"),
                    ("Leather Sofa", "leather-sofa"),
                    ("Corner Sofa", "corner-sofa"),
                ],
            },
            {
                "name": "Recliners",
                "slug": "recliners",
                "image": "recliner",
                "unders": [
                    ("Single Seater Recliners", "single-seater-recliners"),
                    ("Leatherette Recliners", "leatherette-recliners"),
                ],
            },
            {
                "name": "Center Tables",
                "slug": "center-tables",
                "image": "table",
                "unders": [("Wooden Center Tables", "wooden-center-tables")],
            },
        ],
    },
    {
        "name": "Bedroom",
        "slug": "bedroom",
        "featured": True,
        "order": 2,
        "image": "bedroom",
        "subs": [
            {
                "name": "Beds",
                "slug": "beds",
                "image": "bed",
                "unders": [
                    ("King Bed With Storage", "king-bed-with-storage"),
                    ("Queen Bed Without Storage", "queen-bed-without-storage"),
                ],
            },
            {
                "name": "Wardrobes",
                "slug": "wardrobes",
                "image": "wardrobe",
                "unders": [("Three Door Wardrobes", "three-door-wardrobes")],
            },
            {
                "name": "Dressing Tables",
                "slug": "dressing-tables",
                "image": "table",
                "unders": [("Wooden Dressing Tables", "wooden-dressing-tables")],
            },
        ],
    },
    {
        "name": "Dining",
        "slug": "dining",
        "featured": True,
        "order": 3,
        "image": "dining",
        "subs": [
            {
                "name": "Dining Sets",
                "slug": "dining-sets",
                "image": "dining",
                "unders": [
                    ("4 Seater Dining Sets", "4-seater-dining-sets"),
                    ("6 Seater Dining Sets", "6-seater-dining-sets"),
                ],
            },
            {
                "name": "Dining Chairs",
                "slug": "dining-chairs",
                "image": "chair",
                "unders": [("Wooden Dining Chairs", "wooden-dining-chairs")],
            },
        ],
    },
    {
        "name": "Mattresses",
        "slug": "mattresses",
        "featured": True,
        "order": 4,
        "image": "mattress",
        "subs": [
            {
                "name": "Queen Size Mattresses",
                "slug": "queen-size-mattresses",
                "image": "mattress",
                "unders": [],
            },
            {
                "name": "King Size Mattresses",
                "slug": "king-size-mattresses",
                "image": "mattress",
                "unders": [],
            },
        ],
    },
    {
        "name": "Study & Office",
        "slug": "study-office",
        "featured": True,
        "order": 5,
        "image": "study",
        "subs": [
            {
                "name": "Study Tables",
                "slug": "study-tables",
                "image": "study",
                "unders": [("Computer Tables", "computer-tables")],
            },
            {
                "name": "Office Chairs",
                "slug": "office-chairs",
                "image": "chair",
                "unders": [("Gaming Chairs", "gaming-chairs")],
            },
        ],
    },
    {
        "name": "Outdoor",
        "slug": "outdoor",
        "featured": True,
        "order": 6,
        "image": "outdoor",
        "subs": [
            {
                "name": "Outdoor Chairs",
                "slug": "outdoor-chairs",
                "image": "outdoor",
                "unders": [("Patio Chairs", "patio-chairs")],
            },
        ],
    },
    {
        "name": "Decor",
        "slug": "decor",
        "featured": True,
        "order": 7,
        "image": "decor",
        "subs": [
            {"name": "Wall Paintings", "slug": "wall-paintings", "image": "decor", "unders": []},
            {"name": "Clocks", "slug": "clocks", "image": "decor", "unders": []},
            {"name": "Flower Vases", "slug": "flower-vases", "image": "decor", "unders": []},
            {"name": "Buddha Idols", "slug": "buddha-idols", "image": "decor", "unders": []},
            {"name": "Carpets", "slug": "carpets", "image": "decor", "unders": []},
            {"name": "Cushion Covers", "slug": "cushion-covers", "image": "decor", "unders": []},
            {"name": "Showpieces", "slug": "showpieces", "image": "decor", "unders": []},
            {"name": "Table Lamps", "slug": "table-lamps", "image": "decor", "unders": []},
        ],
    },
    {
        "name": "Furnishings",
        "slug": "furnishings",
        "featured": False,
        "order": 8,
        "image": "decor",
        "subs": [
            {"name": "Bedsheets", "slug": "bedsheets", "image": "decor", "unders": []},
            {"name": "Door Mats", "slug": "door-mats", "image": "decor", "unders": []},
        ],
    },
]

# slug, name, brand_slug, category_slug, sub_slug, image_key, sale, mrp, flags
PRODUCTS: list[dict[str, Any]] = [
    {
        "slug": "willow-upholstered-king-bed",
        "name": "Royal Willow Upholstered King Bed",
        "brand": "royal-furniture-pro",
        "category": "bedroom",
        "sub": "beds",
        "under": "king-bed-with-storage",
        "image": "bed",
        "sale": 17000,
        "mrp": 35000,
        "featured": True,
        "best_seller": False,
        "new_arrival": False,
        "trending": True,
    },
    {
        "slug": "blue-hawk-gaming-chair",
        "name": "Royal Blue Hawk Gaming Chair",
        "brand": "royal-furniture-pro",
        "category": "study-office",
        "sub": "office-chairs",
        "under": "gaming-chairs",
        "image": "chair",
        "sale": 7990,
        "mrp": 24999,
        "featured": True,
        "trending": True,
    },
    {
        "slug": "elite-4-seater-dining-set",
        "name": "Royal Elite 4 Seater Wooden Dining Table Set",
        "brand": "malaysian-wood",
        "category": "dining",
        "sub": "dining-sets",
        "under": "4-seater-dining-sets",
        "image": "dining",
        "sale": 22500,
        "mrp": 50000,
        "featured": True,
    },
    {
        "slug": "regal-wooden-king-bed",
        "name": "Royal Regal Wooden King Bed",
        "brand": "malaysian-wood",
        "category": "bedroom",
        "sub": "beds",
        "under": "king-bed-with-storage",
        "image": "bed",
        "sale": 24900,
        "mrp": 65000,
        "featured": True,
        "trending": True,
    },
    {
        "slug": "zen-wooden-dresser",
        "name": "Royal Zen Wooden Dresser",
        "brand": "royal-furniture-pro",
        "category": "bedroom",
        "sub": "dressing-tables",
        "under": "wooden-dressing-tables",
        "image": "table",
        "sale": 5900,
        "mrp": 17000,
        "featured": True,
        "trending": True,
    },
    {
        "slug": "zen-wooden-side-table",
        "name": "Royal Zen Wooden Side Table",
        "brand": "royal-furniture-pro",
        "category": "living",
        "sub": "center-tables",
        "under": "wooden-center-tables",
        "image": "table",
        "sale": 3900,
        "mrp": 9999,
        "featured": True,
    },
    {
        "slug": "nova-leatherette-recliner-brown",
        "name": "Royal Nova Leatherette Single Seater Recliner - Brown",
        "brand": "royal-furniture-pro",
        "category": "living",
        "sub": "recliners",
        "under": "single-seater-recliners",
        "image": "recliner",
        "sale": 14990,
        "mrp": 44999,
        "featured": True,
        "trending": True,
    },
    {
        "slug": "mourya-sofa-set-3-plus-1-plus-1",
        "name": "Royal Mourya Wooden Sofa Set 3+1+1 Grey Cushion",
        "brand": "malaysian-wood",
        "category": "living",
        "sub": "sofas",
        "under": "fabric-sofa",
        "image": "sofa",
        "sale": 36000,
        "mrp": 68600,
        "featured": True,
        "best_seller": True,
    },
    {
        "slug": "ashoka-6-seater-dining-table",
        "name": "Royal Ashoka 6 Seater Sheesham Wood Dining Table",
        "brand": "malaysian-wood",
        "category": "dining",
        "sub": "dining-sets",
        "under": "6-seater-dining-sets",
        "image": "dining",
        "sale": 17500,
        "mrp": 35000,
        "best_seller": True,
    },
    {
        "slug": "serian-wooden-side-table",
        "name": "Royal Serian Wooden Side Table",
        "brand": "royal-furniture-pro",
        "category": "living",
        "sub": "center-tables",
        "under": "wooden-center-tables",
        "image": "table",
        "sale": 3990,
        "mrp": 8899,
        "best_seller": True,
    },
    {
        "slug": "muar-crockery-unit",
        "name": "Royal Muar Malaysian Two Door Crockery Unit",
        "brand": "malaysian-wood",
        "category": "dining",
        "sub": "dining-sets",
        "under": "6-seater-dining-sets",
        "image": "wardrobe",
        "sale": 39999,
        "mrp": 88500,
        "best_seller": True,
    },
    {
        "slug": "polyresin-ganesha-showpiece",
        "name": "Royal Polyresin Ganesha - Bronze & Red - 15.5 Inches",
        "brand": "royal-furniture-pro",
        "category": "decor",
        "sub": "showpieces",
        "under": None,
        "image": "decor",
        "sale": 3498,
        "mrp": 7799,
        "best_seller": True,
    },
    {
        "slug": "naples-3-seater-leather-sofa",
        "name": "Royal Naples Italian 3 Seater Leather Sofa",
        "brand": "italian-living",
        "category": "living",
        "sub": "sofas",
        "under": "leather-sofa",
        "image": "sofa",
        "sale": 65000,
        "mrp": 139000,
        "best_seller": True,
        "trending": True,
    },
    {
        "slug": "logan-computer-table",
        "name": "Royal Logan Computer Table",
        "brand": "royal-furniture-pro",
        "category": "study-office",
        "sub": "study-tables",
        "under": "computer-tables",
        "image": "study",
        "sale": 7499,
        "mrp": 14999,
        "best_seller": True,
    },
    {
        "slug": "sepang-wicker-outdoor-chair",
        "name": "Royal Sepang Malaysian Wicker Outdoor Chair",
        "brand": "malaysian-wood",
        "category": "outdoor",
        "sub": "outdoor-chairs",
        "under": "patio-chairs",
        "image": "outdoor",
        "sale": 5500,
        "mrp": 11999,
        "best_seller": True,
    },
    {
        "slug": "ashoka-dining-chair",
        "name": "Royal Ashoka Sheesham Wood Dining Chair",
        "brand": "malaysian-wood",
        "category": "dining",
        "sub": "dining-chairs",
        "under": "wooden-dining-chairs",
        "image": "chair",
        "sale": 4990,
        "mrp": 14999,
        "new_arrival": True,
    },
    {
        "slug": "florence-fabric-sofa",
        "name": "Royal Florence 3 Seater Fabric Sofa",
        "brand": "italian-living",
        "category": "living",
        "sub": "sofas",
        "under": "fabric-sofa",
        "image": "sofa",
        "sale": 28999,
        "mrp": 54999,
        "new_arrival": True,
        "trending": True,
    },
    {
        "slug": "milano-center-table",
        "name": "Royal Milano Glass Center Table",
        "brand": "italian-living",
        "category": "living",
        "sub": "center-tables",
        "under": "wooden-center-tables",
        "image": "table",
        "sale": 8999,
        "mrp": 18999,
        "new_arrival": True,
        "trending": True,
    },
    {
        "slug": "comfort-queen-mattress",
        "name": "Royal Comfort Queen Size Orthopedic Mattress",
        "brand": "royal-furniture-pro",
        "category": "mattresses",
        "sub": "queen-size-mattresses",
        "under": None,
        "image": "mattress",
        "sale": 12999,
        "mrp": 24999,
        "new_arrival": True,
    },
    {
        "slug": "red-hawk-gaming-chair",
        "name": "Royal Red Hawk Gaming Chair",
        "brand": "royal-furniture-pro",
        "category": "study-office",
        "sub": "office-chairs",
        "under": "gaming-chairs",
        "image": "chair",
        "sale": 7990,
        "mrp": 24999,
        "new_arrival": True,
        "featured": True,
    },
    {
        "slug": "venice-corner-sofa",
        "name": "Royal Venice L-Shaped Corner Sofa",
        "brand": "italian-living",
        "category": "living",
        "sub": "sofas",
        "under": "corner-sofa",
        "image": "sofa",
        "sale": 45999,
        "mrp": 89999,
        "new_arrival": True,
    },
    {
        "slug": "imperial-wardrobe-3-door",
        "name": "Royal Imperial 3 Door Wardrobe",
        "brand": "malaysian-wood",
        "category": "bedroom",
        "sub": "wardrobes",
        "under": "three-door-wardrobes",
        "image": "wardrobe",
        "sale": 18999,
        "mrp": 35999,
        "new_arrival": True,
    },
    {
        "slug": "blossom-wall-painting",
        "name": "Royal Blossom Canvas Wall Painting Set of 3",
        "brand": "royal-furniture-pro",
        "category": "decor",
        "sub": "wall-paintings",
        "under": None,
        "image": "decor",
        "sale": 2499,
        "mrp": 4999,
        "new_arrival": True,
    },
    {
        "slug": "king-comfort-mattress",
        "name": "Royal King Comfort Memory Foam Mattress",
        "brand": "royal-furniture-pro",
        "category": "mattresses",
        "sub": "king-size-mattresses",
        "under": None,
        "image": "mattress",
        "sale": 15999,
        "mrp": 29999,
        "best_seller": True,
    },
]

HERO_BANNERS = [
    {
        "title": "International Furniture, Unbeatable Price",
        "subtitle": "Shop sofas, beds, dining & decor — delivered across India",
        "image": "banner-hero",
        "link": "/living",
        "order": 1,
    },
    {
        "title": "Italian Living Collection",
        "subtitle": "Premium leather sofas & luxury bedroom sets",
        "image": "sofa",
        "link": "/living/sofas",
        "order": 2,
    },
    {
        "title": "No Cost EMI Available",
        "subtitle": "3 & 6 months on HDFC, Axis, SBI & ICICI cards",
        "image": "banner-promo",
        "link": "/dining",
        "order": 3,
    },
    {
        "title": "New Season Arrivals",
        "subtitle": "Fresh designs for living, bedroom & outdoor",
        "image": "bedroom",
        "link": "/bedroom",
        "order": 4,
    },
]

PROMO_BANNERS = [
    {
        "title": "JUMBO OFFER",
        "subtitle": "Flat 70% OFF on selected bestsellers",
        "image": "banner-promo",
        "link": "/living",
        "order": 1,
    },
    {
        "title": "NO COST EMI",
        "subtitle": "On credit cards — min purchase ₹5,000",
        "image": "banner-offer",
        "link": "/dining",
        "order": 2,
    },
]

FEATURE_SETTINGS = [
    {"label": "10M+ customer", "image": "feature"},
    {"label": "International Furniture", "image": "sofa"},
    {"label": "Unbeatable Price", "image": "table"},
    {"label": "100% Secure Payment", "image": "feature"},
    {"label": "No Cost EMI", "image": "feature"},
]

TESTIMONIALS = [
    {
        "name": "Priya Sharma",
        "city": "Bengaluru",
        "text": "Excellent quality sofa set. Delivery was on time and assembly team was professional.",
        "rating": 5,
        "image": "person-1",
    },
    {
        "name": "Rahul Mehta",
        "city": "Mumbai",
        "text": "Bought a dining set during the sale — great value for money. Highly recommend Royal Furniture Pro.",
        "rating": 5,
        "image": "person-2",
    },
    {
        "name": "Ananya Reddy",
        "city": "Hyderabad",
        "text": "The king bed with storage is sturdy and looks premium. Customer support was very helpful.",
        "rating": 5,
        "image": "person-3",
    },
]

FAQS = [
    {
        "category": "Orders",
        "question": "How do I track my order?",
        "answer": "Use Track Order in the header with your order number and registered mobile number.",
    },
    {
        "category": "Delivery",
        "question": "What is the delivery timeline?",
        "answer": "Most metro cities receive delivery within 7–14 business days after order confirmation.",
    },
    {
        "category": "Returns",
        "question": "Can I return a product?",
        "answer": "Damaged or defective items can be reported within 48 hours of delivery for resolution.",
    },
    {
        "category": "Payment",
        "question": "Is No Cost EMI available?",
        "answer": "Yes, 3 and 6 month No Cost EMI is available on select credit cards for orders above ₹5,000.",
    },
]

COUPONS = [
    {
        "code": "ROYAL10",
        "name": "Welcome 10% Off",
        "discount_type": "PERCENTAGE",
        "discount_value": 10,
        "max_discount": 5000,
        "min_order": 5000,
    },
    {
        "code": "FLAT2000",
        "name": "Flat ₹2000 Off",
        "discount_type": "FLAT",
        "discount_value": 2000,
        "max_discount": 2000,
        "min_order": 15000,
    },
]
