[program:royal_gunicorn]
command=/app/.venv/bin/gunicorn config.wsgi:application -c deploy/gunicorn/gunicorn.conf.py
directory=/app
user=www-data
autostart=true
autorestart=true
stdout_logfile=/app/logs/application.log
stderr_logfile=/app/logs/application.log

[program:royal_celery]
command=/app/.venv/bin/celery -A config worker -l info -c 4
directory=/app
autostart=true
autorestart=true

[program:royal_celery_beat]
command=/app/.venv/bin/celery -A config beat -l info
directory=/app
autostart=true
autorestart=true

[program:royal_daphne]
command=/app/.venv/bin/daphne -b 0.0.0.0 -p 8001 config.asgi:application
directory=/app
autostart=true
autorestart=true
